import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AddProductModal } from '../../components/AddProductModal/AddProductModal';
import { EditProductModal } from '../../components/EditProductModal/EditProductModal';
import { ProductService, Product } from '../../services/product.service';

interface ProductFormData {
  name1: string;
  name2: string;
  color: string;
  frameMaterial: string;
  lensMaterial: string;
  price: number | null;
  stock: number | null;
  images: File[];
  description: string;
}

@Component({
  selector: 'product-management-page',
  templateUrl: './ProductManagementPage.html',
  styleUrls: ['./ProductManagementPage.css'],
  standalone: true,
  imports: [CommonModule, FormsModule, AddProductModal, EditProductModal]
})
export class ProductManagementPage implements OnInit {
  private productService = inject(ProductService);
  
  products = signal<Product[]>([]);
  searchTerm: string = '';
  selectedCategory: string = '';
  selectedStatus: string = '';
  selectAll: boolean = false;
  showAddProductModal: boolean = false;
  showEditProductModal: boolean = false;
  productToEdit: Product | null = null;

  ngOnInit(): void {
    this.loadProducts();
  }

  private loadProducts(): void {
    this.productService.getProducts().subscribe({
      next: (products) => {
        // Add selected property for UI management
        const productsWithSelection = products.map(product => ({
          ...product,
          selected: false
        }));
        this.products.set(productsWithSelection);
        console.log('📦 Loaded products for management:', products.length);
      },
      error: (error) => {
        console.error('❌ Error loading products:', error);
        this.products.set([]);
      }
    });
  }

  filteredProducts(): Product[] {
    return this.products().filter(product => {
      const matchesSearch = product.fullName.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
                           product.code.toLowerCase().includes(this.searchTerm.toLowerCase());
      const matchesCategory = !this.selectedCategory || product.category === this.selectedCategory;
      const matchesStatus = !this.selectedStatus || product.status === this.selectedStatus;
      
      return matchesSearch && matchesCategory && matchesStatus;
    });
  }

  toggleSelectAll() {
    const currentProducts = this.products();
    const updatedProducts = currentProducts.map(product => ({
      ...product,
      selected: this.selectAll
    }));
    this.products.set(updatedProducts);
  }

  deleteProduct(id: number) {
    if (confirm('Are you sure you want to delete this product?')) {
      this.productService.deleteProduct(id).subscribe({
        next: (success) => {
          if (success) {
            console.log(`✅ Product with id ${id} deleted successfully`);
            this.loadProducts(); // Reload products after deletion
          } else {
            console.error(`❌ Failed to delete product with id ${id}`);
          }
        },
        error: (error) => {
          console.error('❌ Error deleting product:', error);
        }
      });
    }
  }

  editProduct(id: number) {
    const product = this.products().find(p => p.id === id);
    if (product) {
      this.productToEdit = product;
      this.showEditProductModal = true;
      console.log(`Editing product:`, product);
    }
  }

  openAddProductModal() {
    this.showAddProductModal = true;
  }

  closeAddProductModal() {
    this.showAddProductModal = false;
  }

  closeEditProductModal() {
    this.showEditProductModal = false;
    this.productToEdit = null;
  }

  updateProduct(updatedProduct: Product) {
    this.productService.updateProduct(updatedProduct).subscribe({
      next: (product) => {
        if (product) {
          console.log('✅ Product updated successfully:', product);
          this.loadProducts(); // Reload products to show the updated data
        } else {
          console.error('❌ Failed to update product');
        }
      },
      error: (error) => {
        console.error('❌ Error updating product:', error);
      }
    });
  }

  addNewProduct(productData: ProductFormData) {
    // Create new product object using the Product interface from ProductService
    const newProduct: Product = {
      id: 0, // Will be generated by service
      code: this.generateProductCode(),
      name: productData.name1,
      fullName: `${productData.name1} ${productData.name2}`,
      price: productData.price || 0,
      originalPrice: (productData.price || 0) + 50000, // Add some markup
      stock: productData.stock || 0,
      category: 'Prescription Glasses',
      collection: 'Admin Added',
      status: 'In Stock',
      description: productData.description || 'Product added via admin panel',
      materials: {
        frame: productData.frameMaterial || 'Acetate',
        lens: productData.lensMaterial || 'CR-39',
        temple: 'Acetate reinforced'
      },
      specifications: {
        lensWidth: 52,
        bridgeWidth: 18,
        templeLength: 140,
        frameWidth: 138,
        frameHeight: 42,
        weight: '28g'
      },
      features: ['UV Protection', 'Anti-Glare', 'Lightweight'],
      colors: [
        {
          name: productData.color || 'Black',
          code: '#000000',
          image: 'assets/images/product_items/default.png',
          stock: productData.stock || 0
        }
      ],
      selected: false
    };

    // Use ProductService to add the product
    this.productService.addProduct(newProduct).subscribe({
      next: (addedProduct) => {
        console.log('✅ New product added:', addedProduct);
        this.loadProducts(); // Reload products to show the new one
        this.closeAddProductModal();
      },
      error: (error) => {
        console.error('❌ Error adding product:', error);
      }
    });
  }

  private generateProductCode(): string {
    // Generate a simple product code
    const timestamp = Date.now().toString().slice(-4);
    const random = Math.floor(Math.random() * 100).toString().padStart(2, '0');
    return `PO20${timestamp}${random}`;
  }
}